### ISSUE TITLE
Chinese/English Plates don't drop items

### ISSUE THREAD

**Issue by DarkYuan** [Wouink/furnish#8] opened 2022-03-28 21:46 UTC
Breaking a Chinese Plate or English Plate even with a pickaxe does not drop the plate as an item. Anything in it is simply deleted as well.

**Comment by DWX12** [comment] 2022-06-09 06:51
Wanted to comment on this as well. I've come across ones just spawning in the wild close to or in underground gardens. Not sure if this is intended behavior, but I find it quite strange.

As stated above, they take forever to break and nothing is gained from doing so. I recommend that if anything from Furnish is going to spawn in the wild that it should do so in villages or their own structures.

Thanks for making such a cool mod.

**Comment by Wouink** [comment] 2022-07-22 16:08
Hi, thanks for reporting these issues.

@DarkYuan @DWX12 about the plates not dropping anything, it should be fixed in the new Furnish releases, since `1.18-0.5-fix2`.

@DWX12 Furnish by itself does not add any structure generation! :) However, Enderman can spawn holding rare plates (English Plate and Chinese Plate), which they might then have placed on the ground :thinking:

**Closed by Wouink** 2022-07-22 16:08 UTC
