### ISSUE TITLE
Not sure if this recipe is supposed to be like this but I wanted to check and make sure

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [Wouink/furnish#51] opened 2024-08-01 21:12 UTC
Hello! I've just started using Furnish for the first time but noticed something weird. When I wanted to make a chimney I was looking at the stone brick chimney and it uses Blackstone brick for some reason. Was it meant to be like this or was it supposed to use stone bricks?
![what](https://github.com/user-attachments/assets/c507ce7b-b266-4069-ac8d-ec721b59b8d9)

**Comment by Wouink** [comment] 2024-09-01 12:07
Hi, thanks for reporting.
Duplicate of #47, will be fixed in the next release.

**Closed by Wouink** 2024-09-01 12:07 UTC
